export const environment = {
  apiBaseUrl: 'http://localhost:4200/api/',
  proveedoresEndpoint: 'Proveedores/',
  materialesEndpoint: 'Materiales/',
  facturasEndpoint: 'Facturas/',
  almacenesEndpoint: 'Almacenes/',
  inventariosEndpoint: 'Inventarios/',
  ciudadesEndpoint: 'Ciudades/',
  contratosEndpoint: 'Contratos/',
  clientesEndpoint: 'Clientes/',
  proformasEndpoint: 'Proformas/',
  reportesEndpoint: 'Reportes/',
  loginEndpoint: 'auth/login/',
  registerEndpoint: 'auth/register/',
  checkEmailEndpoint: 'auth/check-email/',
  checkUsernameEndpoint: 'auth/check-username/',
  tokenKey: 'authToken',
};
